language: node_js

node_js:
  - "6.8"

install:
  - npm config set spin=false
  - npm install -g coveralls
  - npm install

script:
  - npm run "coverage:once"
  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false
